<Project>

  <PropertyGroup>
    <RunAnalyzersDuringBuild>false</RunAnalyzersDuringBuild>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <OutputPath>..\$(Configuration)\</OutputPath>
    <LangVersion>Latest</LangVersion>
    <PackageId>LTRData.$(MSBuildProjectName)</PackageId>
    <PackageVersion>1.0.3</PackageVersion>
    <PackageOutputPath>$(LocalNuGetPath)</PackageOutputPath>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

</Project>
