<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Emmellsoft.IoT.Rpi.SenseHat.Tools</RootNamespace>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>

  <PropertyGroup>
    <Title>Emmellsoft.IoT.Rpi.SenseHat.Tools</Title>
    <Company>Emmellsoft</Company>
    <Product>Emmellsoft.IoT.Rpi.SenseHat.Tools</Product>
    <Copyright>Copyright © Emmellsoft 2015</Copyright>
  </PropertyGroup>
  
  <ItemGroup>
    <Compile Include="..\RPi.SenseHat\NativePixelSupport.cs" Link="Linked\NativePixelSupport.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RPi.SenseHat\RPi.SenseHat.csproj" />
    <ProjectReference Include="..\RTIMULibCS\RTIMULibCS.csproj" />
  </ItemGroup>

</Project>
