<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Label="Globals">
    <SccProjectName>SAK</SccProjectName>
    <SccProvider>SAK</SccProvider>
    <SccAuxPath>SAK</SccAuxPath>
    <SccLocalPath>SAK</SccLocalPath>
  </PropertyGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>9.0</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\Rpi.SenseHat\NativePixelSupport.cs" Link="Linked\NativePixelSupport.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RPi.SenseHat\RPi.SenseHat.csproj" />
    <ProjectReference Include="..\RTIMULibCS\RTIMULibCS.csproj" />
  </ItemGroup>

</Project>
